#### Numpy Library 

**Numpy is a python library that allows you to build multidimensional arrays.**

Some array attributes 
 Attribute | returns | Description
 --------- | ------- | ----------- 
 ndarray.ndim | int | number of dimensions
 ndarray.shape | tuple | number of elements in each dimension
 ndarray.size | int | number of elements
 ndarray.dtype | dtype | data type of elements 

`np.array` is a function that returns ndarray object. 

 We can use Numpy for math functions : 
 - We can use all sorts of trigonometric functions.
 - We can use exponential and logarithmic functions. 
 - We also have some mathematical constants. 

To import them we either use : 
 - `import math`
 - `from numpy import cos, sin, pi, nan`

##### Array Creation 
Functions to create arrays : 
 Function | Description
 -------- | ---------- 
 np.zeros | Array filled with zeros
 np.ones(shape) | Array filled with ones
 np.eye(dimension) | This produces the identity matrix
 np.arange(start, stop, step) | creates a one dimensional array
 np.linspace(start, stop, quantity) | Creates a one dimensional array 
 np.vstack([arrays]) and hstack([arrays]) | adds elements from one or more arrays


##### Methods for resizing arrays: 
 Method | Description
 ------ | -----------
 reshape(new_shape) | returns an array with a specific shape
 resize(new_shape) | Modifies the shape of the array being applied

***Note***: Pay attention to which methods modify the array and which returns new array. 

##### Basic operations with arrays 
The arrays in numpy have many functionalities of which they can behave like data structures such as vectors or matrices.

Some of the basic operations and how do arrays behave : 
- Arrays accepts basic operations +, -, *, / and executes them element wise, so arrays must be exactly the same shame 
- Arrays also accept operations with a number (int, float).
- Boolean operations are also accepted and returns an array filled with booleans. 

##### Numpy  Memory management
*Remember that the numpy array is not dynamic also, be careful with objects when copying, manipulating and pasting*.

- To copy an array we use the `.copy()` method. this makes a copy of the array.
**Note that the equal sign does not execute this function**.

###### Property
`.base` : returns the base array that was used to create the current array.

***Note***: We can use the logical operater `is` to checl if we have a new object. 

##### Statistical methods for arrays 

 Method | Description
 ------ | -----------
 max(axis=None) | Returns the maximum value
 min(axis=None) | Returns the minumum value
 argmax(axis=None) | Returns the index of the maximum value
 argmin(axis=None) | Returns the index of the minimum value
 sum(axis=None) | Returns the sum of the array elements
 cumsum(axis=None) | Returns an array with the cumulative sum of the elements
 prod(axis=None) | Returns the product of the array elements 
 cumprod(axis=None) | Returns an array with the cumulative product of the elements
 mean(axis=None) | Returns the mean of the array elements
 var(axis=None) | Returns the Variance of the elements
 std(axis=None) | Returns the standard deviation of the array

**Note**: when the axis option is used, the operation will be performed along the specified axis.

##### Array indexing and slicing

 Operation | Description
 --------- | -----------
 [i] | For one dimensional arrays, it works similar to lists
 [:i] | Displays an array from index 0 until i-1
 [i:] | Displays an array from element i until the last
 [::i] | Displays all the elements varying from i to i
 [::-i] | Displaysthe sequence from back to front of the elements between i and i
 [a:b:c] | start, end , step
 [i,j] | To display an element of a matrix
 [i,a:b] | Returns a slice of row i with elements from a to b
 [n,i,j] | Dimension, Row, Column 


##### Matrices in Numpy 

Numpy arrays can be directly interpreted as matrices

###### Properties 

 `.T` : Returns the transposed matrix 

###### Functions 

 Function | Description 
 -------- | ----------
 np.transpose(A) | Returns the transpose of the matrix A
 np.linalg.det(A) | Returns the determinant of (A)
 np.matmul(A,B) or @ | Returns the matrix multiplication of A by B
 np.matrix | Allows us to perform matrix operations

*** Linalg is a seperate packege from Numpy***


###### Vectors 

 Function | Description
 -------- | -----------
 np.cross(a,b) | Cross product (Array must have at least 2 or 3 elements)
 np.dot(a,b) | Dot Product(Scalar product)
 np.linalg.norm(a) | Returns the norm of the vector 



#### Practice Exercises for the numpy library 
***I'll first be starting with the Exercises from the Python course*** 

##### Exercise 01 : 
**Task**: Create a 2 x 2 matrix fully filled with $\pi$ and Then a 10 x 10 matrix filled with $\pi$ as well


In [5]:
import numpy as np
from numpy import pi 

matrix_2b2 = np.ones((2,2)) * pi
matrix_10b10 = np.ones((10,10)) * pi
print(matrix_2b2)
print(matrix_10b10)



[[3.14159265 3.14159265]
 [3.14159265 3.14159265]]
[[3.14159265 3.14159265 3.14159265 3.14159265 3.14159265 3.14159265
  3.14159265 3.14159265 3.14159265 3.14159265]
 [3.14159265 3.14159265 3.14159265 3.14159265 3.14159265 3.14159265
  3.14159265 3.14159265 3.14159265 3.14159265]
 [3.14159265 3.14159265 3.14159265 3.14159265 3.14159265 3.14159265
  3.14159265 3.14159265 3.14159265 3.14159265]
 [3.14159265 3.14159265 3.14159265 3.14159265 3.14159265 3.14159265
  3.14159265 3.14159265 3.14159265 3.14159265]
 [3.14159265 3.14159265 3.14159265 3.14159265 3.14159265 3.14159265
  3.14159265 3.14159265 3.14159265 3.14159265]
 [3.14159265 3.14159265 3.14159265 3.14159265 3.14159265 3.14159265
  3.14159265 3.14159265 3.14159265 3.14159265]
 [3.14159265 3.14159265 3.14159265 3.14159265 3.14159265 3.14159265
  3.14159265 3.14159265 3.14159265 3.14159265]
 [3.14159265 3.14159265 3.14159265 3.14159265 3.14159265 3.14159265
  3.14159265 3.14159265 3.14159265 3.14159265]
 [3.14159265 3.14159265 3.141

##### Exercise 02 : 
**Task**: Create a 2 x 10 matrix where both rows contain array of integers from 1 to 10
Then change the last number of the matrix from 10 to 100 

In [11]:
import numpy as np
##### This is the first way to do it #####:
print("----- First way -----")
matrix_2b10 = np.array([np.arange(1,11), np.arange(1,11)])
matrix_2b10[::, 9] = 100
print(matrix_2b10)

print("----------------------")
print("----- Second way -----")
##### This is the second way to do it #####:
a = np.arange(1,11)
matrix_2b10_v2 = np.array([a, a])
matrix_2b10_v2[::, 9] = 100
print(matrix_2b10_v2)


----- First way -----
[[  1   2   3   4   5   6   7   8   9 100]
 [  1   2   3   4   5   6   7   8   9 100]]
----------------------
----- Second way -----
[[  1   2   3   4   5   6   7   8   9 100]
 [  1   2   3   4   5   6   7   8   9 100]]


##### Exercise 3 : 
**Task** : Given an array of integers ranging from 0 to 100 return the standard deviation and variance of this array . 

In [12]:
import numpy as np

array_0_to_100 = np.arange(0,101)
std_dev = np.std(array_0_to_100)
variance = np.var(array_0_to_100)
print("Standard Deviation is : ", std_dev)
print("Variance is : ", variance)


Standard Deviation is :  29.154759474226502
Variance is :  850.0


##### Exercise 04 
**Task**: Generate 3 x 10 matrix with random numbers. Then, extract an array with the last three items of the second row 

In [13]:
import numpy as np
import random
matrix_3b10 = np.random.rand(3,10) # Generating 3 x 10 matrix with random numbers
print("The 3x10 matrix with random numbers is : \n", matrix_3b10)
last_three_items_second_row = matrix_3b10[1, -3:] # Extracting last three items of the second row
print("The last three items of the second row are : ", last_three_items_second_row)


The 3x10 matrix with random numbers is : 
 [[0.861287   0.21776474 0.73063691 0.12308798 0.70693272 0.50539698
  0.63261193 0.93021829 0.82043209 0.84552575]
 [0.59116852 0.77083236 0.32951322 0.86850785 0.84766743 0.40218018
  0.15240995 0.65325982 0.4454075  0.12646417]
 [0.92585308 0.62217452 0.68391311 0.29014276 0.78377227 0.86231509
  0.4417208  0.3994713  0.36215179 0.41416104]]
The last three items of the second row are :  [0.65325982 0.4454075  0.12646417]


#### Chat GPT exercises 
***Now i'm moving to the exercises proposed by chat GPT*** 
##### 1. Array Creation 
- Create an array of integers from 0 to 9 
- Create a 1D of 10 zeros, Then create a 1D of 10 one
- Create an array of integers from 10 to 50 with a step of 2
- Create a 3 x 3 identity matrix
- Generate an array of 5 random numbers between 0 and 5

In [14]:
import numpy as np
import random

# Creating an array of integers from 0 to 9
array_0_to_9 = np.arange(10)
print("Array of integers from 0 to 9 : ", array_0_to_9)
# Creating a 1D array of 10 zeros and a 1D array of 10 ones
array_10_zeros = np.zeros(10)
array_10_ones = np.ones(10)
print("1D array of 10 zeros : ", array_10_zeros)
print("1D array of 10 ones : ", array_10_ones)

# Creating an array of integers from 10 to 50 with a step of 2
array_10_to_50_step_2 = np.arange(10, 51, 2)
print("Array of integers from 10 to 50 with a step of 2 : ", array_10_to_50_step_2)
# Creating a 3 x 3 identity matrix
identity_matrix_3b3 = np.eye(3)
print("3 x 3 identity matrix : \n", identity_matrix_3b3)
# Generating an array of 5 random numbers between 0 and 5
array_5_random_0_to_5 = np.random.uniform(0, 5, 5)
print("Array of 5 random numbers between 0 and 5 : ", array_5_random_0_to_5)



Array of integers from 0 to 9 :  [0 1 2 3 4 5 6 7 8 9]
1D array of 10 zeros :  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
1D array of 10 ones :  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Array of integers from 10 to 50 with a step of 2 :  [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]
3 x 3 identity matrix : 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Array of 5 random numbers between 0 and 5 :  [2.48034264 2.80707318 0.19319375 0.84131107 3.08251495]


#### 2. Indexing and slicing 
**Task** : 
- Extract the first three elements of an array `[10,20,30,40,50]`
- Reverse the array `[1,2,3,4,5,6]`
- Given an array `arr=np.arange(25).reshape(5,5)`, extract : 
    - The element in **row 2**, **Column 3**.
    - The entire **First Column**.
    - The **last row**.

In [15]:
import numpy as np
# Extracting the first three elements of an array [10,20,30,40,50]
array_1 = np.array([10,20,30,40,50])
first_three_elements = array_1[:3]
print("First three elements of the array [10,20,30,40,50] are : ", first_three_elements)
print("----------------------")
# Reversing the array [1,2,3,4,5,6]
array_2 = np.array([1,2,3,4,5,6])
reversed_array = array_2[::-1]
print("Reversed array of [1,2,3,4,5,6] is : ", reversed_array)
print("----------------------")
# Given an array arr=np.arange(25).reshape(5,5), extracting the required elements
arr = np.arange(25).reshape(5,5)
element_row2_col3 = arr[1, 2] # Row 2, Column 3 (indexing starts from 0)
first_column = arr[:, 0] # Entire First Column
last_row = arr[-1, :] # Last row
print("Given array arr is : \n", arr)
print("Element in row 2, column 3 is : ", element_row2_col3)
print("Entire first column is : ", first_column)
print("Last row is : ", last_row)



First three elements of the array [10,20,30,40,50] are :  [10 20 30]
----------------------
Reversed array of [1,2,3,4,5,6] is :  [6 5 4 3 2 1]
----------------------
Given array arr is : 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Element in row 2, column 3 is :  7
Entire first column is :  [ 0  5 10 15 20]
Last row is :  [20 21 22 23 24]


#### 3. Array Operations 
**Tasks**:
- Create two arrays `a=np.array([1,2,3])`, `b=np.array([4,5,6])`, Then compute : 
    - `a+b`
    - `a*b`
    - Dot product of `a` and `b`.
- Given an array `x=np.array([2,4,6,8,10])`, Compute : 
    - The mean
    - The standard deviation
    - The sum


In [2]:
import numpy as np
# Creating two arrays and computing their sum , product and dot product
array_a = np.array([1,2,3])
array_b = np.array([4,5,6])
sum_ab = array_a + array_b
product_ab = array_a * array_b
dot_product_ab = np.dot(array_a, array_b)
print("Array a is : ", array_a)
print("Array b is : ", array_b)
print("Sum of a and b is : ", sum_ab)
print("Product of a and b is : ", product_ab)
print("Dot product of a and b is : ", dot_product_ab)
print("----------------------")

# Given an array compute the mean, standard deviation and the sum of all the elements
x = np.array([2,4,6,8,10])
mean_x = np.mean(x)
std_dev_x = np.std(x)
sum_x = np.sum(x)
print("Given array x is : ", x)
print("Mean of x is : ", mean_x)
print("Standard Deviation of x is : ", std_dev_x)
print("Sum of all elements in x is : ", sum_x)

Array a is :  [1 2 3]
Array b is :  [4 5 6]
Sum of a and b is :  [5 7 9]
Product of a and b is :  [ 4 10 18]
Dot product of a and b is :  32
----------------------
Given array x is :  [ 2  4  6  8 10]
Mean of x is :  6.0
Standard Deviation of x is :  2.8284271247461903
Sum of all elements in x is :  30


### Reshaping and stacking 
**Tasks** : 
- Create an array of numbers from 1 to 12 then reshape into a 3 x 4 matrix